// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hero.proto

package hero

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Hero struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{0}
}

func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (m *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(m, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Hero) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetHerosReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHerosReq) Reset()         { *m = GetHerosReq{} }
func (m *GetHerosReq) String() string { return proto.CompactTextString(m) }
func (*GetHerosReq) ProtoMessage()    {}
func (*GetHerosReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{1}
}

func (m *GetHerosReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHerosReq.Unmarshal(m, b)
}
func (m *GetHerosReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHerosReq.Marshal(b, m, deterministic)
}
func (m *GetHerosReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHerosReq.Merge(m, src)
}
func (m *GetHerosReq) XXX_Size() int {
	return xxx_messageInfo_GetHerosReq.Size(m)
}
func (m *GetHerosReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHerosReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHerosReq proto.InternalMessageInfo

type GetHerosRes struct {
	Heros                []*Hero  `protobuf:"bytes,1,rep,name=heros,proto3" json:"heros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHerosRes) Reset()         { *m = GetHerosRes{} }
func (m *GetHerosRes) String() string { return proto.CompactTextString(m) }
func (*GetHerosRes) ProtoMessage()    {}
func (*GetHerosRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{2}
}

func (m *GetHerosRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHerosRes.Unmarshal(m, b)
}
func (m *GetHerosRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHerosRes.Marshal(b, m, deterministic)
}
func (m *GetHerosRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHerosRes.Merge(m, src)
}
func (m *GetHerosRes) XXX_Size() int {
	return xxx_messageInfo_GetHerosRes.Size(m)
}
func (m *GetHerosRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHerosRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetHerosRes proto.InternalMessageInfo

func (m *GetHerosRes) GetHeros() []*Hero {
	if m != nil {
		return m.Heros
	}
	return nil
}

type GetHeroReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHeroReq) Reset()         { *m = GetHeroReq{} }
func (m *GetHeroReq) String() string { return proto.CompactTextString(m) }
func (*GetHeroReq) ProtoMessage()    {}
func (*GetHeroReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{3}
}

func (m *GetHeroReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeroReq.Unmarshal(m, b)
}
func (m *GetHeroReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeroReq.Marshal(b, m, deterministic)
}
func (m *GetHeroReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeroReq.Merge(m, src)
}
func (m *GetHeroReq) XXX_Size() int {
	return xxx_messageInfo_GetHeroReq.Size(m)
}
func (m *GetHeroReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeroReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeroReq proto.InternalMessageInfo

func (m *GetHeroReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetHeroRes struct {
	Hero                 *Hero    `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHeroRes) Reset()         { *m = GetHeroRes{} }
func (m *GetHeroRes) String() string { return proto.CompactTextString(m) }
func (*GetHeroRes) ProtoMessage()    {}
func (*GetHeroRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{4}
}

func (m *GetHeroRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHeroRes.Unmarshal(m, b)
}
func (m *GetHeroRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHeroRes.Marshal(b, m, deterministic)
}
func (m *GetHeroRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHeroRes.Merge(m, src)
}
func (m *GetHeroRes) XXX_Size() int {
	return xxx_messageInfo_GetHeroRes.Size(m)
}
func (m *GetHeroRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHeroRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetHeroRes proto.InternalMessageInfo

func (m *GetHeroRes) GetHero() *Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

type SaveHeroReq struct {
	Hero                 *Hero    `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveHeroReq) Reset()         { *m = SaveHeroReq{} }
func (m *SaveHeroReq) String() string { return proto.CompactTextString(m) }
func (*SaveHeroReq) ProtoMessage()    {}
func (*SaveHeroReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{5}
}

func (m *SaveHeroReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveHeroReq.Unmarshal(m, b)
}
func (m *SaveHeroReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveHeroReq.Marshal(b, m, deterministic)
}
func (m *SaveHeroReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveHeroReq.Merge(m, src)
}
func (m *SaveHeroReq) XXX_Size() int {
	return xxx_messageInfo_SaveHeroReq.Size(m)
}
func (m *SaveHeroReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveHeroReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveHeroReq proto.InternalMessageInfo

func (m *SaveHeroReq) GetHero() *Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

type SaveHeroRes struct {
	Hero                 *Hero    `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveHeroRes) Reset()         { *m = SaveHeroRes{} }
func (m *SaveHeroRes) String() string { return proto.CompactTextString(m) }
func (*SaveHeroRes) ProtoMessage()    {}
func (*SaveHeroRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{6}
}

func (m *SaveHeroRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveHeroRes.Unmarshal(m, b)
}
func (m *SaveHeroRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveHeroRes.Marshal(b, m, deterministic)
}
func (m *SaveHeroRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveHeroRes.Merge(m, src)
}
func (m *SaveHeroRes) XXX_Size() int {
	return xxx_messageInfo_SaveHeroRes.Size(m)
}
func (m *SaveHeroRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveHeroRes.DiscardUnknown(m)
}

var xxx_messageInfo_SaveHeroRes proto.InternalMessageInfo

func (m *SaveHeroRes) GetHero() *Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

type DeleteHeroReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHeroReq) Reset()         { *m = DeleteHeroReq{} }
func (m *DeleteHeroReq) String() string { return proto.CompactTextString(m) }
func (*DeleteHeroReq) ProtoMessage()    {}
func (*DeleteHeroReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{7}
}

func (m *DeleteHeroReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHeroReq.Unmarshal(m, b)
}
func (m *DeleteHeroReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHeroReq.Marshal(b, m, deterministic)
}
func (m *DeleteHeroReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHeroReq.Merge(m, src)
}
func (m *DeleteHeroReq) XXX_Size() int {
	return xxx_messageInfo_DeleteHeroReq.Size(m)
}
func (m *DeleteHeroReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHeroReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHeroReq proto.InternalMessageInfo

func (m *DeleteHeroReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteHeroRes struct {
	Hero                 *Hero    `protobuf:"bytes,1,opt,name=hero,proto3" json:"hero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHeroRes) Reset()         { *m = DeleteHeroRes{} }
func (m *DeleteHeroRes) String() string { return proto.CompactTextString(m) }
func (*DeleteHeroRes) ProtoMessage()    {}
func (*DeleteHeroRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c95cb63f3700114, []int{8}
}

func (m *DeleteHeroRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHeroRes.Unmarshal(m, b)
}
func (m *DeleteHeroRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHeroRes.Marshal(b, m, deterministic)
}
func (m *DeleteHeroRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHeroRes.Merge(m, src)
}
func (m *DeleteHeroRes) XXX_Size() int {
	return xxx_messageInfo_DeleteHeroRes.Size(m)
}
func (m *DeleteHeroRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHeroRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHeroRes proto.InternalMessageInfo

func (m *DeleteHeroRes) GetHero() *Hero {
	if m != nil {
		return m.Hero
	}
	return nil
}

func init() {
	proto.RegisterType((*Hero)(nil), "Hero")
	proto.RegisterType((*GetHerosReq)(nil), "GetHerosReq")
	proto.RegisterType((*GetHerosRes)(nil), "GetHerosRes")
	proto.RegisterType((*GetHeroReq)(nil), "GetHeroReq")
	proto.RegisterType((*GetHeroRes)(nil), "GetHeroRes")
	proto.RegisterType((*SaveHeroReq)(nil), "SaveHeroReq")
	proto.RegisterType((*SaveHeroRes)(nil), "SaveHeroRes")
	proto.RegisterType((*DeleteHeroReq)(nil), "DeleteHeroReq")
	proto.RegisterType((*DeleteHeroRes)(nil), "DeleteHeroRes")
}

func init() { proto.RegisterFile("proto/hero.proto", fileDescriptor_2c95cb63f3700114) }

var fileDescriptor_2c95cb63f3700114 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x98, 0x54, 0x3a, 0xdb, 0x16, 0x99, 0x53, 0x8c, 0x82, 0x61, 0x3d, 0x74, 0xc9,
	0x61, 0x85, 0xfa, 0x0a, 0x82, 0x9e, 0xb7, 0x4f, 0x10, 0xcd, 0xa0, 0x01, 0x35, 0x76, 0x27, 0xe4,
	0x9d, 0x7c, 0x4b, 0xd9, 0x6d, 0xd5, 0x8d, 0x60, 0xe8, 0x6d, 0xbe, 0x99, 0x3f, 0x7f, 0x66, 0x7e,
	0x16, 0xce, 0x3e, 0x5c, 0xd7, 0x77, 0x37, 0x2f, 0xe4, 0x3a, 0x13, 0x4a, 0x55, 0x41, 0xfa, 0x40,
	0xae, 0xc3, 0x15, 0x24, 0x6d, 0x93, 0x8b, 0x52, 0xe8, 0xcc, 0x26, 0x6d, 0x83, 0x08, 0xe9, 0x7b,
	0xfd, 0x46, 0x79, 0x52, 0x0a, 0x3d, 0xb7, 0xa1, 0x56, 0x4b, 0x90, 0xf7, 0xd4, 0x7b, 0x39, 0x5b,
	0xda, 0xa9, 0x2a, 0x46, 0xc6, 0x0b, 0xc8, 0xbc, 0x2f, 0xe7, 0xa2, 0x3c, 0xd1, 0x72, 0x93, 0x19,
	0x3f, 0xb1, 0xfb, 0x9e, 0xba, 0x04, 0x38, 0x68, 0x2d, 0xed, 0xfe, 0xfe, 0x4c, 0xad, 0xa3, 0x29,
	0xe3, 0x39, 0xa4, 0xfe, 0xa3, 0x30, 0xff, 0xf1, 0x09, 0x2d, 0xa5, 0x41, 0x6e, 0xeb, 0x81, 0xbe,
	0x7d, 0x8e, 0x55, 0x4e, 0x7a, 0x5e, 0xc1, 0xf2, 0x8e, 0x5e, 0xa9, 0xa7, 0xff, 0xb6, 0xab, 0xc6,
	0x82, 0x29, 0xb3, 0xcd, 0xa7, 0x00, 0xe9, 0x71, 0x4b, 0x6e, 0x68, 0x9f, 0x08, 0xd7, 0x30, 0x7f,
	0xde, 0x5f, 0x46, 0x8c, 0x0b, 0x13, 0xc5, 0x57, 0xc4, 0xc4, 0x78, 0x0d, 0xa7, 0x07, 0x21, 0x4a,
	0xf3, 0x1b, 0x55, 0x11, 0x01, 0xa3, 0x82, 0x94, 0xeb, 0x81, 0x70, 0x61, 0xa2, 0x14, 0x8a, 0x98,
	0x18, 0x35, 0xcc, 0x9a, 0xb0, 0x2d, 0xae, 0xcc, 0xe8, 0xae, 0x62, 0xcc, 0xfc, 0x38, 0x0b, 0x2f,
	0xe0, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x98, 0x5c, 0x8f, 0x02, 0x15, 0x02, 0x00, 0x00,
}
